### ISSUE TITLE
lower performance than P2P client

### ISSUE THREAD

**Issue by hugogong** [johang/btfs#46]
I found that download performance through btfs in ubuntu is lower than BT client, such like uTorrent.
The BTFS is installed by command:
apt-get install btfs

I execute command like:
btfs <torrent seed file> /mnt
rsync -av /mnt/* /root/Desktop/testfolder

It there anything need to set to enhance it?

**Comment by johang** [comment]
Yeah, btfs is not optimized for performance. It will have huge overhead if you have a download with large block size and you do small reads. Each read call will trigger at least one whole block read, regardless of read size. Also, download priority changed slightly in 2.18. With 2.18 total download speed will be higher, but might have higher read latency.

**Comment by hugogong** [comment]
I tried  v2.18 on ubuntu. however, the performance looks bad either against multiple or single big size file(s).   :-(

**Comment by aurora-of-earth** [comment]
@hugogong @johang 
One reason may be because btfs does fetch the torrent from the first block as it should logically do, so that a playable media file would play correctly.
ntfs is not a BitTorrent client in the sense of qBittorrent and uTorrent, etc.
A real BitTorrent client can retrieve any piece of a file from the BitTorrent network, wether at the beginning, the middle or at the end.
